### ISSUE TITLE
[Suggestion] Early-Game-Buckets Compatibility 

### ISSUE THREAD

**Issue by NealSavage** [Nosrick/crock-pot-mod#10]
At the moment, if you right click the crockpot with a bucket from the Early-Game-Bucket mod, it does nothing. Could you make it compatible please? Here's the link to the mod in question. https://www.curseforge.com/minecraft/mc-mods/early-game-buckets

**Comment by Nosrick** [comment]
I've actually been meaning to make it so that data packs can be used to add items to the bucket list (pun intended), so I'll work on that today!

**Comment by Nosrick** [comment]
It's a little janky, but #12 adds Early-Game Buckets compatibility to this!

As an added bonus, items can now be tagged as "infinite" or "consumable" sources of water for the crock pot.
Just uploading to Curse now.
Let me know how it goes!

**Comment by NealSavage** [comment]
The wood and ceramic buckets from Early-Game-Buckets do now work! Thanks! :)

As to the infinite thing, I am not sure what you mean. I assumed you meant the no more than 8 types of foods in it one and tested it. If it is that, the fix hasn't worked. I'm now thinking you meant a config option that lets you choose whether or not you ever have to refill the crockpot after filling it up once, even if you use all the portions? But, I'm not seeing a config option for that.

**Comment by Nosrick** [comment]
What I mean by "consumable" is an item that is "used up" when it is used to fill the crock pot; buckets, for example, which will empty themselves of water when used to fill the crock pot.
By "infinite" I mean an item that is _not_ used up when it is used to fill the crock pot. The only item that currently does this is the Heart of the Sea, which will fill the crock pot any time you use it and never break.

**Comment by NealSavage** [comment]
Ahh okay! That makes sense!
