### ISSUE TITLE
Incompatibility of Sodium Mod

### ISSUE THREAD

**Issue by CCCClear** [Nosrick/crock-pot-mod#13]
1.18.2 latest version.
After testing, I can confirm that the cause of the blackening of the crock is the Sodium mod (single mod test), but I do not know the cause of the blackening.

**Comment by Nosrick** [comment]
I'll see what I can do about this, thanks for reporting!

**Comment by Filaipus** [comment]
Thanks for figuring that out, was wondering what was going on. Nosrick, let us know if you need some logs

**Comment by Nosrick** [comment]
Turns out I can't do anything about it, but Indium seems to fix this!

Give me a shout if you're okay closing this issue.
