### ISSUE TITLE
[1.18.2] Crock Pots are black even with Indium installed

### ISSUE THREAD

**Issue by esotericdesign** [Nosrick/crock-pot-mod#18]
A similar issue has already been closed; the solution of using Sodium with Indium doesn't work for me. Tested with Fabric API, Sodium and Indium only.
Mod version: 1.12.0
Fabric API version: 0.58.0
Sodium 0.4.1+build 15
Indium 1.0.7

**Comment by Nosrick** [comment]
I'll take a look into this and see what's happening. Thanks for reporting it, and apologies for the slow reply!

**Comment by Nosrick** [comment]
This seems to be something to do with how Sodium has changed the way world chunks fetch BlockEntities.
I'm not sure if this is a problem on my end, or a problem on theirs. Further investigation pending.

**Comment by Nosrick** [comment]
Just an update that this seems to be a Sodium problem, which the CaffeineMC team don't seem to be addressing, so I'm not sure how to proceed here.

**Comment by Nosrick** [comment]
Hi, just to let you know; I think I've managed to fix this!
I'll be releasing a new version with some pretty big fixes in general pretty soon, so keep an eye out for that.
