### ISSUE TITLE
Disconnect on Empty Hand Right-Click with Sodium

### ISSUE THREAD

**Issue by BioMasterZap** [Nosrick/crock-pot-mod#23]
I saw there have been some previous issues similar to this but didn't see this exact problem or any for this version so figured it might be worth reporting. This is on Fabric 1.20.4 with Crockpot 1.14.0 and Sodium 0.5.8. If I attempt to right-click a Crockpot with an empty hand, I get booted from the world (singleplayer in this case) with the message "Internal Exception: java.lang.IllegalStateException: Accessing OpenGL function from outside the main render thread is not supported when using Sodium" and get put back on the multiplayer menu. It seems to still work fine for adding water, adding ingredients, and taking stew, just not right-clicking with an empty hand.

This was verified on a test profile with only Crockpot 1.14.0, Cloth Config 13.0.121 (the same happened without it), Sodium 0.5.8. and Fabric APU 0.96.0. Without Sodium, right-clicking with an empty hand does not disconnect. Here is the full log: https://gist.github.com/BioMasterZap/462b59400319c8647d7e4446fe1c5d5c

**Comment by Nosrick** [comment]
Thanks for reporting this. I'll look into it when I get a moment to do so, but this is fairly low on my priority list for now. It might be a simple fix, but if it's related to Sodium, this is unlikely to be the case.

**Comment by Nosrick** [comment]
I take that back. It might have been an extremely easy fix. Try out this .jar for me and let me know if it's fixed that issue. If it has, I'll release it as a quick patch.

Edit to add: that log was absolutely invaluable, thank you so much!

[crockpot-1.14.1+1.20.4.zip](https://github.com/Nosrick/crock-pot-mod/files/14402480/crockpot-1.14.1%2B1.20.4.zip)

**Comment by BioMasterZap** [comment]
Only saw this a bit ago and didn't do the most extensive testing, but it seems like that resolved the issue.

**Comment by Nosrick** [comment]
Perfect! I'll shot that up on the actual release page later this week.
