### ISSUE TITLE
another crock pot crash with sodium

### ISSUE THREAD

**Issue by Withrill** [Nosrick/crock-pot-mod#25]
@Nosrick 
right-clicking on the pot ontop of campfire disconnected me with this error message

![crackpot](https://github.com/Nosrick/crock-pot-mod/assets/30693341/bdc189d3-eeca-477b-b9f4-9ce1e7cef1e6)

this was on the 1.20.2 version btw, i hope it gets fixed very soon because i'm tryna enjoy this mod in a modded server with friends

**Comment by Withrill** [comment]
also using minecraft fabric 
earlier before i opened this issue, i was using indium thinking it'd fix it but nope

crockpot-1.13.3+1.20.2.jar
sodium-fabric-mc1.20.2-0.5.5
indium-1.0.28+mc1.20.4.jar (unsure whether its relevant or not)

**Comment by Nosrick** [comment]
Thank you for reporting this!
I'll put out the fix for this version alongside the 1.20.5 update today.

**Comment by Nosrick** [comment]
Alright, that should be it updated. Crash is gone on my end, but let me know if it isn't fixed.

**Comment by Withrill** [comment]
Thanks, it no longer crashes anymore and there doesn't seem to be any other issue I notice so far
