### ISSUE TITLE
not compatable with impersonate? bewitchment? origins?

### ISSUE THREAD

**Issue by TheRanker** [Nosrick/crock-pot-mod#3]
https://github.com/Ladysnake/Impersonate/issues/23

**Comment by TheRanker** [comment]
had this issue .. reported it to them... found out.. it was crock pot causing the issue. removing crockpot and everything was perf.

**Comment by Nosrick** [comment]
I'll take a look into it, but I use two mixins; one for tooltips, one for food. Might be Impersonate's mixins, but it could easily be mine.
Thank you for reporting this!

**Comment by Nosrick** [comment]
Just a quick update: I cannot reproduce this crash with just Crock Pot, Impersonate and Bewitchment. There is something _very, very_ odd going on here, but I cannot figure out what it is.
The log points to an ARRP failure, but Crock Pot does not use that library at all, so I have no idea why removing Crock Pot makes the whole thing work.
There's a smokescreen here, and it's going to take me a long time to actually figure it out.

Can you link me to your mod pack, or zip your mods folder and upload it somewhere for me?

**Comment by TheRanker** [comment]
i cant seem to replicate the issue at all now myself.  it loads correctly now.  so basically ive updated about 15 mods.. and tried crock pot again... to start gathering info,, and it works. lol

you may close this .. ill do a new ticket if i happent o come across this again :)

**Comment by Nosrick** [comment]
lol I'm glad you got it working!
(also glad I didn't have to spend all day fiddling with compat stuff)
