### ISSUE TITLE
I put this suggestion here because I don't know where else to put it

### ISSUE THREAD

**Issue by Harambesadvocate** [Nosrick/crock-pot-mod#4]
An idea for redstone thingy, maybe it could be powered instead by turning switching on the lever connected redstone trail which is connected to crock pot or maybe even by switching on the lever right on the block next to the crock pot on which redstone used.

**Comment by Nosrick** [comment]
Thank you so much!

**Comment by Harambesadvocate** [comment]
You are welcome

**Comment by Nosrick** [comment]
That's it done! It'll be in the next release, once I get a few more features in.
