### ISSUE TITLE
Issue with Crock Pot Menu

### ISSUE THREAD

**Issue by NealSavage** [Nosrick/crock-pot-mod#6]
My fried eggs from Better Animals Plus just give me a purple-black missing asset texture in the crockpot menu. Though, the leeks from Croptopia do work. And, the fried eggs show up correctly once in inventory. 

Images are attached.

![image](https://user-images.githubusercontent.com/4138801/164291790-8a699483-5008-444a-a026-ae7dd3db42c9.png)
![image](https://user-images.githubusercontent.com/4138801/164291842-b7ba5bb3-7209-4d27-ac3a-fcba36eff7f4.png)

**Comment by Nosrick** [comment]
Huh, that's an interesting one. I'll take a look at it in the morning, thank you for reporting this!

What version are you using?

Edit: It looks like you don't use Appleskin, but you do use WTHIT, right?

**Comment by NealSavage** [comment]
I don't use Appleskin, and I do use WTHIT, correct. 

1.18.2 Fabric is my version.

**Comment by NealSavage** [comment]
And, the mod version I have downloaded is crockpot-0.8.1+1.18.2

**Comment by Nosrick** [comment]
Thanks! I'll take a look into it in the next few hours.
I'm guessing it's something dumb like I'm not using the same code for the viewing tooltips as I am for the item tooltips haha.

**Comment by Nosrick** [comment]
I found the cause: BetterAnimalsPlus do not use standard conventions for their asset locations.
Minecraft uses `textures/item/beef.png` whereas BetterAnimalsPlus uses `textures/items/fried_egg.png`, so it's items with an s. My texture grabbing code for my WTHIT plugin can't find it, which is slightly irritating, and is what's causing the problem.

I'm working on a bit of a fix now.

**Comment by Nosrick** [comment]
I think I got it!
Uploading a new version to CurseForge atm, check for it in a few minutes when it's been approved.
![image](https://user-images.githubusercontent.com/1487089/164413722-02f7cc96-8dc9-4e4d-8c80-f9d8dd4210a9.png)

**Comment by NealSavage** [comment]
Ahh, that's an interesting problem! The latest mod version seems to have addressed the problem! :)
